

var googleLinks =[
	'##AMP-AD',
	'###center_col > #\5f Emc',
	'###center_col > #main > .dfrd > .mnr-c > .c._oc._zs',
	'###center_col > #res > #topstuff + #search > div > #ires > #rso > #flun',
	'###center_col > #resultStats + #tads',
	'###center_col > #resultStats + #tads + #res + #tads',
	'###center_col > #resultStats + div + #res + #tads',
	'###center_col > #resultStats + div[style="border:1px solid #dedede;margin-bottom:11px;padding:5px 7px 5px 6px"]',
	'###center_col > #taw > #tvcap > .rscontainer',
	'###center_col > div[style="font-size:14px;margin-right:0;min-height:5px"] > div[style="font-size:14px;margin:0 4px;padding:1px 5px;background:#fff8e7"]',
	'###cnt #center_col > #res > #topstuff > .ts',
	'###cnt #center_col > #taw > #tvcap > .c._oc._Lp',
	'###main_col > #center_col div[style="font-size:14px;margin:0 4px;padding:1px 5px;background:#fff7ed"]',
	'###mbEnd[cellspacing="0"][cellpadding="0"]',
	'###mclip_container:last-child',
	'###mn #center_col > div > h2.spon:first-child',
	'###mn #center_col > div > h2.spon:first-child + ol:last-child',
	'###mn div[style="position:relative"] > #center_col > ._Ak',
	'###mn div[style="position:relative"] > #center_col > div > ._dPg',
	'###resultspanel > #topads',
	'###rhs_block .mod > .gws-local-hotels__booking-module',
	'###rhs_block .mod > .luhb-div > div[data-async-type="updateHotelBookingModule"]',
	'###rhs_block .xpdopen > ._OKe > div > .mod > ._yYf',
	'###rhs_block > #mbEnd',
	'###rhs_block > .ts[cellspacing="0"][cellpadding="0"][style="padding:0"]',
	'###rhs_block > ol > .rhsvw > .kp-blk > .xpdopen > ._OKe > ol > ._DJe > .luhb-div',
	'###rhs_block > script + .c._oc._Ve.rhsvw',
	'###rhswrapper > #rhssection[border="0"][bgcolor="#ffffff"]',
	'###ssmiwdiv[jsdisplay]',
	'###tads + div + .c',
	'###tads.c',
	'###tadsb.c',
	'###tadsto.c',
	'###topstuff > #tads',
	'##.GB3L-QEDGY .GB3L-QEDF- > .GB3L-QEDE-',
	'##.GFYY1SVD2 > .GFYY1SVC2 > .GFYY1SVF5',
	'##.GFYY1SVE2 > .GFYY1SVD2 > .GFYY1SVG5',
	'##.GHOFUQ5BG2 > .GHOFUQ5BF2 > .GHOFUQ5BG5',
	'##.GJJKPX2N1 > .GJJKPX2M1 > .GJJKPX2P4',
	'##.GKJYXHBF2 > .GKJYXHBE2 > .GKJYXHBH5',
	'##.GPMV2XEDA2 > .GPMV2XEDP1 > .GPMV2XEDJBB',
	'##.ch[onclick="ga(this,event)"]',
	'##.commercial-unit-desktop-rhs',
	'##.commercial-unit-desktop-top',
	'##.commercial-unit-mobile-bottom',
	'##.commercial-unit-mobile-top',
	'##.lads[width="100%"][style="background:#FFF8DD"]',
	'##.mod > ._jH + .rscontainer',
	'##.mw > #rcnt > #center_col > #taw > #tvcap > .c',
	'##.mw > #rcnt > #center_col > #taw > .c',
	'##.ra[align="left"][width="30%"]',
	'##.ra[align="right"][width="30%"]',
	'##.ra[width="30%"][align="right"] + table[width="70%"][cellpadding="0"]',
	'##.rhsvw[style="background-color:#fff;margin:0 0 14px;padding-bottom:1px;padding-top:1px;"]',
	'##.rscontainer > .ellip',
	'##.section-result[data-result-ad-type]',
	'##.widget-pane-section-result[data-result-ad-type]'
]